//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf_PorductosNetofice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Productos
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad { get; set; }
        public bool Estado { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public string Usuario { get; set; }
        public string TransactionId { get; set; }
    }
}
